<a href="https://colab.research.google.com/github/Ashraful1Islam/MachineLearning_DataScience/blob/main/Numpy_indexing_Selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
import numpy as np


In [40]:
# create a 1D array
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
# accesses the value at index 8
arr[8]

np.int64(8)

In [42]:
#slice the array from index 1 to 4
arr[1:5]

array([1, 2, 3, 4])

In [43]:
#slice the array from begining to index 4
arr[0:5]

array([0, 1, 2, 3, 4])

In [44]:
# this is same like [0,5]
arr[:5]

array([0, 1, 2, 3, 4])

In [45]:
#slicing from index 5 to end
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [46]:
# slice assignment
arr[0:5]=100 # this replace the first 5 elements with the value 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [47]:
arr=np.arange(0,11)#Reinitialize
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
#Creates a view (not a copy) of the first 6 elements
slice_of_arr=arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [49]:
#Changes all values in the view to 99. Since this is a view, it also updates the original arr.

slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [50]:
#Creates a true copy of arr. Changes to arr_copy will NOT affect the original.
arr_copy=arr.copy()
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [51]:
#Sets all values in the copy to 100. Original arr remains unchanged.
arr_copy[:]=100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [52]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

**2D array Indexing**


In [53]:
# Creates a 2D NumPy array (3x3 matrix).
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [54]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [55]:
# Accesses row 1, column 1 (25).we could also write arr_2d[1, 1].
arr_2d[1][1]

np.int64(25)

In [56]:
#Slice first 2 rows (row 0 and 1), and columns from index 1 to the end. Result:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [57]:
#Takes the first 2 rows:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

BOOLEAN INDEXING

In [58]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
#Creates a boolean array where each position is True if the value is greater than 5.
bool_arr=arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [60]:
# Filters out only the elements where the boolean array is True: [6 7 8 9 10]
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [61]:
 #Same as above, but written in one line.
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [62]:
# Filters for elements less than 3: [1 2]
arr[arr<3]

array([1, 2])

2D ARRAY SLICE EXPLANATION

In [63]:
# Creates a 1D array from 0 to 49, and reshapes it into a 5x10 matrix.
arr_2d=np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [64]:
#Slices from row 1 to row 2 (remember: end is exclusive), so we get rows 1 and 2:
arr_2d[1:3,]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [65]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])