<a href="https://colab.research.google.com/github/Ashraful1Islam/MachineLearning_DataScience/blob/main/Numpy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
# Convert list into array
import numpy as np
my_list=[1,2,3,4]
np.array(my_list)#Output -> array([1, 2, 3, 4])
#if we input nested list
my_list1=[[1,2,3],[5,6,7],[8,9,10]]
np.array(my_list1) #output 2D array

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [7]:
#we can arrange number by arange function
np.arange(0,10)#output ->rray([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.arange(0,12,2)#0 theke shuru and 12 porjonto,2 step por por ->rray([ 0,  2,  4,  6,  8, 10])


array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3)#array([0., 0., 0.])
np.zeros((3,3))#2D matrix 3 column 3 rows of 0
np.ones(3)#same like zeros
np.ones((3,3))# same like zeros

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
#linspace (0,5,10) ,,0 theke 5 porjnto 10 ti element
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [15]:
#Random function
np.random.rand(5)#5 ti random number in 1D array,but all are in floating
np.random.randn(4)#4 ti random normal distribution element,,mean 0 standard deviation 1
np.random.randint(0,10,10)# min 0 max 10 er mddhe 10 ti element

array([3, 1, 7, 0, 2, 1, 2, 6, 0, 5])

In [33]:
#shape related
arr=np.random.randint(0,12,9)
arr
arr.reshape(3,3)# 3X3 a shape kora holo
arr.max()#max element
arr.min()#min element
arr.argmax()#index of max element
arr.argmin()#index of min element
arr.shape

(9,)